name: Secrets and Environment Variables

on: 
  workflow_dispatch

jobs:
  top-secret:
    runs-on: ubuntu-latest
    env: 
      API_KEY: ${{ secrets.API_KEY }}
    
    steps:
      - name: Prueba del yml
        run: echo "Hola desde el repositorio"
