name: Secrets and Enviorment Variables

on: 
  workflow_dispatch

job:
  top-secret:
    runs-on: ubuntu-latest
    env: ${{ secrets.API_KEY }}
    
    steps:
      - name: Prueba del yml
        run: echo "Hola desde el repositorio"