name: Secrets and Environment Variables

on: 
  workflow_dispatch

jobs:
  top-secret:
    runs-on: ubuntu-latest
    env: 
      API_KEY: ${{ secrets.API_KEY }}
      ENC_ID: ${{ vars.ENC_ID }}
    
    steps:
      - name: Prueba del yml
        run: echo "Hola desde el repositorio"
      - name: Variable de entorno
        run: echo "Hola desde el repositorio $ {{ ENC_ID }}"
        
