name: Secrets and Environment Variables

on: 
  workflow_dispatch

jobs:
  top-secret:
    runs-on: ubuntu-latest
    env: 
      API_KEY: ${{ secrets.API_KEY }}
      ENC_ID: ${{ vars.ENC_ID }}
      DB_SQL: ${{ secrets.DB_SQL }}
      TRAD_PERRO: ${{ vars.TRAD_EN_PERRO }}
    
    steps:
      - name: Prueba del yml
        run: echo "Hola desde el repositorio"
      - name: Variable de entorno
        run: echo "Hola desde el repositorio ${{ env.API_KEY }}"
      - name: Cadena de Conexion a SQL
        run: echo "Hola desde el repositorio cadena de conexion ${{ env.DB_SQL }}"
      - name: Traduccion de Perro a ingles
        run: echo "Hola desde el repositorio traduccion ${{ env.TRAD_PERRO }}"

